[versions]
# libraries
kotlinTarget = "2.4"
javaTarget = "17"
kotlin = "2.4.10"
xemanticKotlinTest = "1.17.5"
asm = "9.9.1"
# plugins
versionCatalogUpdatePlugin = "1.1.1"
dokkaPlugin = "2.2.0"
mavenPublishPlugin = "0.37.0"
jreleaserPlugin = "1.25.0"
binaryCompatibilityValidatorPlugin = "0.18.1"
xemanticConventionsPlugin = "0.7.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
xemantic-kotlin-test = { module = "com.xemantic.kotlin:xemantic-kotlin-test", version.ref = "xemanticKotlinTest" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-plugin-power-assert = { id = "org.jetbrains.kotlin.plugin.power-assert", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokkaPlugin" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdatePlugin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublishPlugin" }
kotlinx-binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryCompatibilityValidatorPlugin" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaserPlugin" }
xemantic-conventions = { id = "com.xemantic.gradle.xemantic-conventions", version.ref = "xemanticConventionsPlugin" }
